#!/bin/sh
# Run the ZeroPRC server for the director
# Copyright (c) 2014 Clarinova. This file is licensed under the terms of the
# Revised BSD License, included in this distribution as LICENSE.txt

exec python -mipydoc.server $@